server:
  port: 8189
  servlet:
    context-path: /library
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/libraryDB?currentSchema=hiber
    username: postgres
    password: postgres
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL94Dialect
      open-in-view: false

pagination:
  page-size: 3